name: Test
on:
  push:
    branches-ignore:
      - datastore
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEBUG: ghkv
jobs:
  get-set:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
      - run: node example.js set answer 42
      - run: node example.js get answer | grep 42
  counter:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
      - run: node example.js test:counter
      - run: node example.js test:counter-concurrent
